### ISSUE TITLE
Confirmation email after feedback is submitted

### ISSUE THREAD

**Issue by elenadanailova** [nworbnhoj/qwikgame#34]
Confirmation email should be sent back to the author after a feedback is submitted.
Since we cannot know what the feedback will be (positive or negative), a simply "thank you" mail should be enough. Something like: "Thank you for your feedback!"

**Comment by nworbnhoj** [comment]
Sending an email to an arbitrary address based on the submission of the form on a web page will almost certainly result in the form being used as a mail relay. That is, the form will be discovered by bots and used by spammers to distribute email. This would result in qwikgame being tagged as a spammer and blocked by most email servers. Not ideal.

This email-relay scenario can be mitigated by using a captcha or a qwik quiz (as currently used to mitigate the same threat for the email validation for a new qwik player). But this is a PITA for the user.

Another alternative is to simply say "thank you" when the feedback form is submitted - with a popup (sometime blocked by browsers) or a message when the form page refreshes.

**Comment by elenadanailova** [comment]
In this case, just a simple "Thank you" on the website right after the form is submitted, would be better. Because I don't think people would be happy to pass "I'm not a robot quiz" just to receive a thank you message.

But why then the user needs to complete his/her email address right after completing the feedback? What is it needed for?
