### ISSUE TITLE
Center Pick time to play

### ISSUE THREAD

**Issue by elenadanailova** [nworbnhoj/qwikgame#81]
Center 'Pick time to play' just like 'Awaiting Players to accept'.

![image](https://github.com/user-attachments/assets/f0998eac-cf7b-4d92-9237-91ec71194e40)

**Comment by nworbnhoj** [comment]
To be consistent with all other Fields on the site - the Label should be capitalized and left-aligned. And following this lead - the hour-blocks should be left-aligned.
![Screenshot from 2024-12-19 13-27-15](https://github.com/user-attachments/assets/1e4b39f3-1d00-49a2-9d97-69f4bf1d717b)

**Comment by nworbnhoj** [comment]
Please comment below if it is important to make an exception in this instance. Such an exception would involve constructing a specialized field_label template with the various associated elements  and css

```
<!-- qwikgame/templates/field_label.html -->
<div class="label">
    {{ field.label_tag }}
{% if field.field.url %}
    <a href="{% url field.field.url %}">{{ field.field.sub_text }}</a>
{% elif field.field.sub_text %}
    <span class='sub_text'>{{ field.field.sub_text }}</span>
{% endif %}
{% if field.help_text %}
    <div class='info_text hidden'>{{ field.help_text|safe }}</div>
    <div class="btn secondary small round push_right info" data-visible="false">
        <i class="fa-solid fa-info fa-1x" aria-hidden="true"></i>
    </div>
{% endif %}
</div>
````
