### ISSUE TITLE
Inconsistent Match hours between header and log entries

### ISSUE THREAD

**Issue by elenadanailova** [nworbnhoj/qwikgame#82]
Some bug appears with the hours after match is scheduled. It happened 3 out of 4 times. Initially I thought it's something related to the time zones because I was scheduling matches in other countries. Then I tested 2 times for BG venues only. The first one went well, the second one - bug again:

Match was scheduled for 19h (well visible from Invitation history). However, in the circle it appears as 17h. In the Orange banner it also appears as 17h

![image](https://github.com/user-attachments/assets/843bad6d-59b0-43d0-82ba-fb6bd563f965)

Another example: Match was scheduled for 22h but in the same places as above it shows wrong hour (11h):

![image](https://github.com/user-attachments/assets/ed08cd27-a4d6-48e7-96e0-38e8d9c50bf9)

**Comment by elenadanailova** [comment]
https://alpha.qwikgame.org/game/match/94/

https://alpha.qwikgame.org/game/match/88/

**Comment by nworbnhoj** [comment]
two learnings

1. The Django DateTimeField drops the tzinfo info from an aware datetime when stored (and stores in utc)
2.  pytz is unreliable for daylight savind zones! https://til.codeinthehole.com/posts/to-prefer-dateutil-over-pytz/
