### ISSUE TITLE
Hour buttons fixed size

### ISSUE THREAD

**Issue by elenadanailova** [nworbnhoj/qwikgame#86]
The hour buttons should always be the same size on Desktop.
In this screenshot, the size for TOMORROW is better.

I see this difference is not there on Mobile and the size is good.

![image](https://github.com/user-attachments/assets/fa93967b-c6f1-4e3b-b121-cfdf8bab961c)

**Comment by nworbnhoj** [comment]
resolved by 41caf2e34fb2fa8a2f25d8b0f883285e07e4a8ba
