### ISSUE TITLE
Refine next-up msg for Appeal status = dormant or cancelled

### ISSUE THREAD

**Issue by nworbnhoj** [nworbnhoj/qwikgame#91]
![Screenshot_20241215-170619.png](https://github.com/user-attachments/assets/59470ce7-8ba9-4a86-aab3-dd5d6149c55a)

The next-up message should reflect an Appeal that has been Confirmed as a Match (dormant) or Cancelled.

Suggest:

Dormant: A Match has been confirmet for this Invitation.

Cancelled: This Invitation has been cancelled.

**Comment by elenadanailova** [comment]
Sorry, could you please elaborate a bit more on this? I don't get it.

**Comment by nworbnhoj** [comment]
In the screen shot above, _nhoj_ has cancelled the Appeal, but the _nextup_ message advises that the Appeal is "Awaiting Players to accept". The _nextup_ should perhaps be "This Invitation has been cancelled."

There is another situation, when a Match has been scheduled, but the Appeal remains visible to allow the non-successful Bidders to see what happened. The next up message should probably be "A Match has been confirmet for this Invitation." rather than "Awaiting Players to accept"
