### ISSUE TITLE
Accepting an appeal: Put option "cancel" under 3 dots next to the Profile pic

### ISSUE THREAD

**Issue by elenadanailova** [nworbnhoj/qwikgame#93]
When I accept an invitation (place a bid) please, put option "cancel" under 3 dots next to my profile pic (in this case "0")

![image](https://github.com/user-attachments/assets/446ee211-9b69-4754-820d-831cd03f680a)

**Comment by nworbnhoj** [comment]
This seemingly small change probably requires a major redesign and rebuild of the structures associated with the Appeal/Bid log_entries. Each of these log entries were designed as a simple tupple appended to a log - and for the log to be simply displayed in sequential order. 

There is, for example, no current way of determining which of these log entries represents an active-Bid and which a retracted-Bid. To keep track of such matters would require machinery to traverse the log-entries and match each bid with its retraction, and then to display a cancel option only to an active-Bid made by the current Player viewing the log. Certainly possible, but considerably different to the current implementation designed to append a passive tupple to then end of a list.
